@localhost=localhost:4004/odata/v4/main

@id=1139ae8a-e517-4aae-b86e-ece7ec5bec8a

GET http://{{localhost}}/Customers
Content-Type: application/json

### 

POST http://{{localhost}}/Customers
Content-Type: application/json
 
{
    "id": "b3278f9c-4575-451d-906f-67763641d6a0",
    "firstName": "Kelsu",
    "lastName": "Damasxeno",
    "email": "kel.damasxeno@gmail.com"
}
 

###

DELETE http://{{localhost}}/Customers
Content-Type: application/json

###

PUT http://{{localhost}}/Customers
Content-Type: application/json

###

###Buscar pedidos que não conteham -
GET http://localhost:4004/odata/v4/main/Customers?$filter=not endswith(firstName,'-23')
Content-Type: application/json

# entity Customers {
#    key id: UUID;
#       firstName: String(20);
#       lastName: String(100);
#       email: String(255);
# }
