@localhost=localhost:4004/odata/v4/main

@id=0e979026-a6c1-46eb-b199-205031f9543a

@customerId=1139ae8a-e517-4aae-b86e-ece7ec5bec8a

@productId=a2e1e82e-c2dc-4af8-a207-59601020e445

GET http://localhost:4004/odata/v4/main/SalesOrderHeaders
Content-Type: application/json

###

POST http://localhost:4004/odata/v4/main/SalesOrderHeaders
Content-Type: application/json

{
    "id": "{{id}}",
    "customer_id": "{{customerId}}",
    "totalAmount": 699,
    "items": [
        {
            "id": "9795763d-3228-474b-b553-23e38a8dfc95",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 10,
            "price": 3.99
        },

        {
            "id": "bf66c933-656b-420b-a8c1-0a9b0a3b03d6",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 5,
            "price": 3.00
        }
    ] 
}

###

DELETE http://localhost:4004/odata/v4/main/SalesOrderHeaders(id={{id}})
Content-Type: application/json

###

PUT http://localhost:4004/odata/v4/main/SalesOrderHeaders(id={{id}})
Content-Type: application/json

###

## Buscar pedidos maiores ou iguais a um x valor
GET http://localhost:4004/odata/v4/main/SalesOrderHeaders?$filter=totalAmount ge 200
Content-Type: application/json

###

## Buscar pedidos maiores ou iguais a um x valor
GET http://localhost:4004/odata/v4/main/SalesOrderHeaders?$filter=totalAmount le 200
Content-Type: application/json



